version: '3.1'
services:
  orthanc:
    image: jodogne/orthanc-plugins:1.12.2
    command: /run/secrets/
    ports:
      - 4242:4242
      - 8042:8042
    secrets:
      - orthanc.json
    environment:
      - ORTHANC_NAME=NAMIC
    volumes:
      - orthanc_db:/var/lib/orthaxnc/db

  hapi-fhir-jpaserver-start:
    build: hapi-fhir/.
    restart: on-failure
    ports:
      - "8080:8080"
  hapi-fhir-postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: "hapi"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - hapi-fhir-postgres:/var/lib/postgresql/data
volumes:
  hapi-fhir-postgres:
  orthanc_db:
secrets:
  orthanc.json:
    file: orthanc.json
